apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  version: "1.0"
spec:
  replicas: 2  # nbr de replication                     
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: aghilasob/product_app:01
        ports:
        - containerPort: 5000  # Port sur  app coute dans le container

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80        # Port d'exposition externe
    targetPort: 5000  # Redirection vers le port interne du container
  type: LoadBalancer 
