apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: aghilasob/product_app:01
          imagePullPolicy: Always   
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 5000  
  type: LoadBalancer    

---
# gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: product-gateway
spec:
  selector:
    istio: ingressgateway   # Utilise l’Istio ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
# virtual service

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - product-gateway
  http:
    - match:
        - uri:
            prefix: /product
        - uri:
            exact: /
      route:
        - destination:
            host: product-service
            port:
              number: 80
